[package]
name = "ksni"
version = "0.2.1"
authors = ["iovxw <iovxw@outlook.com>"]
edition = "2018"
description = """
A Rust implementation of the KDE/freedesktop StatusNotifierItem specification
"""
repository = "https://github.com/iovxw/ksni"
keywords = ["systray", "linux", "gui"]
categories = ["api-bindings"]
license = "Unlicense"

[dependencies]
futures = { version = "0.3.28", default-features = false }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["rt", "macros"] }
zbus = { version = "4.1.2", features = ["tokio"], default-features = false }
